// members
export const MEMBERS_DELETE = "MEMBERS/DELETE";
export const MEMBERS_REVIEW = "MEMBERS/REVIEW";
export const MEMBERS_SET_REVIEW = "MEMBERS/SET_REVIEW";
export const MEMBERS_UPDATE_STATUS = "MEMBERS/UPDATE_STATUS";
export const MEMBERS_CREATE = "MEMBERS/CREATE";
export const MEMBERS_FETCH = "MEMBERS/FETCH";
export const MEMBERS_SET = "MEMBERS/SET";

// seasons
export const SEASONS_DELETE = "SEASONS/DELETE";
export const SEASONS_EDIT = "SEASON/EDIT";
export const SEASONS_SET_EDIT = "SEASON/SET_EDIT";
export const SEASONS_UPDATE_EDIT = "SEASON/UPDATE_EDIT";
export const SEASONS_CREATE = "SEASONS/CREATE";
export const SEASONS_FETCH = "SEASONS/FETCH";
export const SEASONS_SET = "SEASONS/SET";

// server messages
export const MESSAGE_HIDE = "MESSAGE/HIDE";
export const MESSAGE_RESET = "MESSAGE/RESET";
export const MESSAGE_SET = "MESSAGE/SET";

// user authethenication
export const USER_PASSWORD_UPDATE = "USER/PASSWORD_UPDATE";
export const USER_PASSWORD_RESET = "USER/PASSWORD_RESET";
export const USER_SIGNIN = "USER/SIGNIN";
export const USER_SIGNIN_ATTEMPT = "USER/SIGNIN_ATTEMPT";
export const USER_SIGNIN_SESSION = "USER/SIGNIN_SESSION";
export const USER_SIGNOUT = "USER/SIGNOUT";
export const USER_SIGNOUT_SESSION = "USER/SIGNOUT_SESSION";
export const USER_SIGNUP = "USER/SIGNUP";
