// events
export const EVENTS_CREATE = "EVENTS/CREATE";
export const EVENTS_DELETE = "EVENTS/DELETE";
export const EVENTS_EDIT = "EVENTS/EDIT";
export const EVENTS_FETCH = "EVENTS/FETCH";
export const EVENTS_INIT_NEW_EVENT = "EVENTS/INIT_NEW_EVENT";
export const EVENTS_SET = "EVENTS/SET";
export const EVENTS_SET_EDIT = "EVENTS/SET_EDIT";
export const EVENTS_SET_NEW_EVENT = "EVENTS/SET_NEW_EVENT";
export const EVENTS_UPDATE = "EVENTS/UPDATE";

export const EVENTS_FETCH_SCHEDULE_EVENTS = "EVENTS/FETCH_SCHEDULE_EVENTS";
export const EVENTS_SET_SCHEDULE_EVENTS = "EVENTS/SET_SCHEDULE_EVENTS";

export const EVENTS_FETCH_SCHEDULE = "EVENTS/FETCH_SCHEDULE";
export const EVENTS_SET_SCHEDULE = "EVENTS/SET_SCHEDULE";
export const EVENTS_UPDATE_SCHEDULE = "EVENTS/UPDATE_SCHEDULE";

// forms
export const FORMS_CREATE = "FORMS/CREATE";
export const FORMS_DELETE = "FORMS/DELETE";
export const FORMS_EDIT = "FORMS/EDIT";
export const FORMS_FETCH = "FORMS/FETCH";
export const FORMS_FETCH_AP = "FORMS/AP_FETCH";
export const FORMS_SET = "FORMS/SET";
export const FORMS_SET_EDIT = "FORMS/SET_EDIT";
export const FORMS_UPDATE = "FORMS/UPDATE";
export const FORMS_SET_AP = "FORMS/SET_AP";
export const FORMS_UPDATE_AP = "FORMS/UPDATE_AP";

// members
export const MEMBERS_CREATE = "MEMBERS/CREATE";
export const MEMBERS_DELETE = "MEMBERS/DELETE";
export const MEMBERS_FETCH = "MEMBERS/FETCH";
export const MEMBERS_FETCH_AVAILABILITY = "MEMBERS/FETCH_AVAILABILITY";
export const MEMBERS_FETCH_EVENTS = "MEMBERS/FETCH_EVENTS";
export const MEMBERS_FETCH_NAMES = "MEMBERS/FETCH_NAMES";
export const MEMBERS_REVIEW = "MEMBERS/REVIEW";
export const MEMBERS_SET = "MEMBERS/SET";
export const MEMBERS_SET_AVAILABILITY = "MEMBERS/SET_AVAILABILITY";
export const MEMBERS_SET_NAMES = "MEMBERS/SET_NAMES";
export const MEMBERS_SET_EVENTS = "MEMBERS/SET_EVENTS";
export const MEMBERS_SET_REVIEW = "MEMBERS/SET_REVIEW";
export const MEMBERS_UPDATE = "MEMBERS/UPDATE";
export const MEMBERS_UPDATE_STATUS = "MEMBERS/UPDATE_STATUS";

export const MEMBERS_DELETE_TOKEN = "MEMBERS/DELETE_TOKEN";
export const MEMBERS_FETCH_TOKEN = "MEMBERS/FETCH_TOKEN";
export const MEMBERS_SET_TOKEN = "MEMBERS/SET_TOKEN";
export const MEMBERS_UPDATE_TOKEN = "MEMBERS_UPDATE_TOKEN";

export const MEMBERS_FETCH_TOKENS = "MEMBERS/FETCH_TOKENS";
export const MEMBERS_SET_TOKENS = "MEMBERS/SET_TOKENS";

// seasons
export const SEASONS_DELETE = "SEASONS/DELETE";
export const SEASONS_EDIT = "SEASONS/EDIT";
export const SEASONS_SET_EDIT = "SEASONS/SET_EDIT";
export const SEASONS_UPDATE_EDIT = "SEASONS/UPDATE_EDIT";
export const SEASONS_CREATE = "SEASONS/CREATE";
export const SEASONS_FETCH = "SEASONS/FETCH";
export const SEASONS_FETCH_IDS = "SEASONS/FETCH_IDS";
export const SEASONS_SET = "SEASONS/SET";
export const SEASONS_SET_IDS = "SEASONS/SET_IDS";

// mail
export const MAIL_CREATE = "MAIL/CREATE";
export const MAIL_DELETE = "MAIL/DELETE";
export const MAIL_EDIT = "MAIL/EDIT";
export const MAIL_FETCH = "MAIL/FETCH";
export const MAIL_RESEND = "MAIL/RESEND";
export const MAIL_SET = "MAIL/SET";
export const MAIL_SET_EDIT = "MAIL/SET_EDIT";
export const MAIL_UPDATE_EDIT = "MAIL/UPDATE_EDIT";

// server messages
export const MESSAGE_HIDE = "MESSAGE/HIDE";
export const MESSAGE_RESET = "MESSAGE/RESET";
export const MESSAGE_SET = "MESSAGE/SET";

// user authethenication
export const USER_PASSWORD_UPDATE = "USER/PASSWORD_UPDATE";
export const USER_PASSWORD_RESET = "USER/PASSWORD_RESET";
export const USER_SIGNIN = "USER/SIGNIN";
export const USER_SIGNIN_ATTEMPT = "USER/SIGNIN_ATTEMPT";
export const USER_SIGNIN_SESSION = "USER/SIGNIN_SESSION";
export const USER_SIGNOUT = "USER/SIGNOUT";
export const USER_SIGNOUT_SESSION = "USER/SIGNOUT_SESSION";
export const USER_SIGNUP = "USER/SIGNUP";
