/* istanbul ignore file */

export default [
	{
		name: "seasonId",
		type: "select",
		label: "Season ID",
		placeholder: "Select a season id...",
		icon: "id",
		value: "",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: [],
	},
	{
		name: "league",
		type: "select",
		label: "League",
		placeholder: "Select a league...",
		icon: "puck",
		value: "NHL",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: ["NHL", "AHL"],
	},
	{
		name: "eventType",
		type: "select",
		label: "Event Type",
		placeholder: "Select a league...",
		icon: "calander",
		value: "Game",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: ["Game", "Promotional", "Other"],
	},
	{
		name: "location",
		type: "text",
		label: "Event Location",
		icon: "location",
		value: "",
		errors: "",
		placeholder: "Optional (default is SAP Center)",
		required: false,
		disabled: true,
	},
	{
		type: "range",
		name: "eventDates",
		label: "Event Dates",
		tooltip:
			"Please select a start date, start time, end date, and an end time.",
		value: [],
		errors: "",
		required: true,
		format: "MM/DD/YYYY h:mm a",
		showTime: { format: "h:mm a", use12Hours: true, minuteStep: 15 },
		style: { width: "100%" },
	},
	{
		type: "time",
		name: "callTime",
		label: "Scheduling Call Times",
		placeholder: "Select a call time...",
		value: null,
		errors: "",
		required: true,
		style: { width: "100%" },
	},
];
