/* istanbul ignore file */

export default [
	{
		name: "seasonId",
		type: "select",
		label: "Season ID",
		placeholder: "Select a season id...",
		icon: "id",
		value: "",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: [],
	},
	{
		name: "league",
		type: "select",
		label: "League",
		placeholder: "Select a league...",
		icon: "puck",
		value: "NHL",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: ["NHL", "AHL"],
	},
	{
		name: "eventType",
		type: "select",
		label: "Event Type",
		placeholder: "Select a league...",
		icon: "calander",
		value: "Game",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: ["Game", "Promotional", "Other"],
	},
	{
		name: "location",
		type: "text",
		label: "Event Location",
		icon: "location",
		value: "SAP Center at San Jose",
		errors: "",
		placeholder: "Enter an event location...",
		required: true,
		disabled: true,
	},
	{
		type: "range",
		name: "eventDates",
		label: "Event Dates",
		tooltip:
			"Please select a start date, start time, end date, and an end time.",
		value: [],
		errors: "",
		required: true,
		format: "MM/DD/YYYY h:mm a",
		showTime: { format: "h:mm a", use12Hours: true, minuteStep: 15 },
		style: { width: "100%" },
	},
	{
		name: "uniform",
		type: "select",
		label: "Event Attire",
		placeholder: "Select a uniform...",
		icon: "tshirt",
		value: "Teal Jersey",
		errors: "",
		required: true,
		disabled: true,
		selectOptions: [
			"Sharks Teal Jersey",
			"Sharks Black Jersey",
			"Sharks Jacket",
			"Barracuda Jacket",
			"Other",
		],
	},
	{
		name: "notes",
		type: "textarea",
		label: "Event Notes",
		value: "",
		errors: "",
		placeholder: "(Optional) Include any special event notes...",
		required: false,
		disabled: true,
	},
	{
		type: "time",
		name: "callTime",
		label: "Scheduling Call Times",
		placeholder: "Select a call time...",
		value: null,
		errors: "",
		required: true,
		style: { width: "100%" },
	},
];
