/* istanbul ignore file */
export default [
	{
		name: "sendTo",
		type: "transfer",
		label: "Send To",
		tooltip:
			"Select and transfer one or multiple members from the left box to the right box to include them on the mailing list.",
		value: [],
		errors: "",
		required: true,
		disabled: true,
		dataSource: [],
		showSearch: true,
		listStyle: {
			width: 277,
			height: 300,
		},
		rowKey: record => record.email,
	},
	{
		name: "sendFrom",
		type: "text",
		label: "Send From",
		placeholder: "An email address to send from...",
		tooltip:
			"Include your own email if you wish to override the default below.",
		icon: "id",
		value: "San Jose Sharks Ice Team <noreply@sjsiceteam.com>",
		errors: "",
		required: true,
		disabled: true,
	},
	{
		type: "date",
		name: "sendDate",
		label: "Send Date",
		placeholder: "*Optional* Select a send date and time...",
		tooltip:
			"Select a time below if you wish to send this email at a later date.",
		value: null,
		errors: "",
		required: false,
		disabled: true,
		format: "MM/DD/YYYY h:mm a",
		showTime: { format: "h:mm a", use12Hours: true, minuteStep: 15 },
		style: { width: "100%" },
	},
	{
		name: "subject",
		type: "input",
		label: "Subject",
		icon: "mail",
		value: "",
		errors: "",
		placeholder: "The subject of the email...",
		required: true,
		disabled: true,
	},
	{
		name: "message",
		type: "editor",
		label: "Message",
		value: "",
		errors: "",
		placeholder: "Type a message...",
		required: true,
		disabled: true,
	},
];
