/* istanbul ignore file */
export default [
	{
		name: "email",
		type: "email",
		label: "Authorized Email",
		icon: "mail",
		value: "",
		errors: "",
		required: true,
	},
	{
		name: "firstName",
		type: "text",
		label: "First Name",
		icon: "user",
		value: "",
		errors: "",
		required: true,
	},
	{
		name: "lastName",
		type: "text",
		label: "Last Name",
		icon: "user",
		value: "",
		errors: "",
		required: true,
	},
	{
		name: "role",
		type: "select",
		label: "Role",
		placeholder: "Select an option...",
		icon: "usertag",
		value: "",
		errors: "",
		required: true,
		selectOptions: ["staff", "employee"],
	},
];
